# Generated by Django 4.1.3 on 2022-11-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Travels', models.CharField(max_length=200)),
                ('Name_Manager', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
