# Generated by Django 4.1.3 on 2022-11-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_about_contact_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='travel',
        ),
        migrations.AddField(
            model_name='about',
            name='travels',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
