# Generated by Django 4.0.3 on 2022-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_busdetails_destination_payment_route_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Name_Manager',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Name_Travels',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='sahoo@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Lost Something', max_length=30),
        ),
    ]
