# Generated by Django 4.1 on 2022-11-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customer_bus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bus_No',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='bus_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='destination',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='driver_phono',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='origin',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
