# Generated by Django 4.1 on 2022-11-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact_bus_no_contact_bus_name_contact_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('bus_name', models.CharField(max_length=200)),
                ('aadhar_no', models.IntegerField(default=True, null=True)),
                ('origin', models.CharField(default=True, max_length=100)),
                ('destination', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
            ],
        ),
    ]
