# Generated by Django 4.1 on 2022-11-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ticket_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_history',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='ticket_history',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket_history',
            name='start_time',
        ),
    ]
