# Generated by Django 4.1 on 2022-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ticket_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='type',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
