# Generated by Django 4.1 on 2022-12-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_busdetails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar_no',
            field=models.IntegerField(default=True, max_length=12, null=True),
        ),
    ]
