# Generated by Django 4.1 on 2022-12-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customer_aadhar_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origins', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='aadhar_no',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.origin'),
        ),
    ]
