# Generated by Django 4.1 on 2022-12-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_origin_alter_customer_aadhar_no_alter_route_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='froms',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.origin'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(max_length=200),
        ),
    ]
