# Generated by Django 4.1 on 2022-12-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_route_froms_alter_route_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='froms',
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.origin'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.destination'),
        ),
    ]
