# Generated by Django 4.1 on 2022-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_route_froms_alter_route_destination_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
